### ISSUE TITLE
Implementing SQLite for storing logs

### ISSUE THREAD

**Issue by jindalpriyanshu101** [BOSS294/AutoMatic-File-Generator---PYTHON--#6]
### Discussed in https://github.com/BOSS294/AutoMatic-File-Generator---PYTHON--/discussions/5

<div type='discussions-op-text'>

> ### SQL LITE INTEGRATION 
> Let's integrate SQLITE with our software so that it can record the total logs
Which directory was created by who , When & Where
GUI will now have buttons to show Creating Logs

Working on it, i'll be storing directory logs data into a .db file using sqlite for users locally.

**Comment by BOSS294** [comment]
Locked
